---
name: SparkX-Form-Field-Email
version: 0.01
author:
  - 'James Laver <sprintf qw(%s@%s.%s cpan jameslaver com)>'
abstract: An email field for Spark::Form. Implements Spark::Form::Field::Role::Regex
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Any::Moose: 0
  Spark::Form: '>=0.01'
build_requires:
  Test::More: 0
provides:
  SparkX::Form::Field::Email:
    file: lib/SparkX/Form/Field/Email.pm
    version: 0.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
